### ISSUE TITLE
Better error for inferred primary key on view

### ISSUE THREAD

**Issue by abrthel** [rom-rb/rom-sql#147]
When defining a schema for a view the primary key must be explicitly defined as a view can not have a primary key set and as a result it can not be inferred. 

If a view's relation schema does not define a pk then a command like `person_repo.update(1, fullname: 'James')` raises
```
/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-3.0.1/lib/rom/schema.rb:164:in `[]': nil attribute doesn't exist in people schema (KeyError)
```
which is unhelpful in rooting out the true cause.

**Comment by flash-gordon** [comment]
btw views can have PK constraint, there is nothing special about it because it's just a record in the dictionary, not a real constraint. Some RDBMS, such as Oracle, supports this but this is defo a rare feature
you can vote for PG support here https://postgresql.uservoice.com/forums/21853-general/suggestions/388585-add-primary-key-to-view-definition :)

**Comment by abrthel** [comment]
Huh, the things you learn. Though my experiences with RDBMSs is pretty limited to postgresql, mysql and sqlite. Either way that's a pretty cool tip. Thanks!
