### ISSUE TITLE
Alternativ definition of joins

### ISSUE THREAD

**Issue by choallin** [rom-rb/rom-sql#182]
Right now I must define a join like this ```inner_join(:booking, {payingbp_id: :id})``` if I don't have a foreign key in the database and the fields do not match the convention.
If I have multiple joins, a join always refers to the relation that calls the join. If I want to access an other relation I have to write it this way:
```inner_join(:address, {businesspartner_id: :businesspartnerbase__id})```
Right now there is no syntax to avoid the underscores.
Maybe it would be good to have something like this:
```
inner_join(:address, {address[businesspartner_id].qualified => :businesspartnerbase[:id].qualified})
```

**Comment by solnic** [comment]
@flash-gordon are you aware of any alternative way of doing this where underscores are not used?

**Comment by flash-gordon** [comment]
```ruby
associations do
  has_many :addresses, foreign_key: ...
end

inner_join(:addresses)
```

this might do the trick^

**Comment by solnic** [comment]
oh it's a different problem:

``` ruby
users.
  join(:tasks, user_id: :id).  # :id => users.id is assumed
  join(:tags, task_id: :tasks__id) # here you need to qualify explicitly, otherwise :id will be ambiguous
```

so, since we want to remove support for underscores, we need an alternative way of specifying which join keys must be used (or which relation, then join keys can be inferred). Since we're calling join methods on `users` then this is the base, so its associations are used, but we're joining `tasks=>tags`, so it's tricky.

**Comment by solnic** [comment]
Starting from 2.0.0 all schemas are qualified by default so this should no longer be a problem. Closing.
