### ISSUE TITLE
Fix build for jruby-9000

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-sql#49]
https://travis-ci.org/rom-rb/rom-sql/jobs/92706354

**Comment by flash-gordon** [comment]
That was interesting... First of all, the fail you see caused by quite poorly maintained pg_jdbc gem. I sent a PR about the issue https://github.com/headius/jruby-pg/pull/32 After fixing it on my local my machine I found that now specs are failing at equality check [here](https://github.com/rom-rb/rom-sql/blob/master/spec/integration/association/one_to_one_spec.rb#L37) because SQLite on jdbc returns Fixnum instead of BigDecimal despite table field was declared as numeric. Everything works fine if we return 10000.1 instead of a round number so I spent some time searching for the root of the problem. It turned out that jdbc-sqlite [uses result type in the first place](https://bitbucket.org/xerial/sqlite-jdbc/src/8de652d3f54cdfd32d5a493130c995f36e16c652/src/main/java/org/sqlite/RS.java?at=default&fileviewer=file-view-default#RS.java-859:887) (see L859) and only after that it looks at the field type which leads to a really silly bug (it is a bug, am I right?): your column value will have different types depending on what value was in the first record of the result set. WAT
I'll try to use jdbc-postgres instead of pg_jdbc and will raise an issue on the jdbc-sqlite's bitbucket (I'm not sure if they'll fix it). ugh

**Comment by flash-gordon** [comment]
OK, they moved to GH. The code remained [the same](https://github.com/xerial/sqlite-jdbc/blob/master/src/main/java/org/sqlite/jdbc3/JDBC3ResultSet.java#L731-L759).

**Comment by flash-gordon** [comment]
I raised an issue https://github.com/xerial/sqlite-jdbc/issues/112
I doubt it will be resolved though, I think we should update the specs to use fraction values for balance field. Oh god, what a hack...

**Comment by solnic** [comment]
Can we make a special case spec for jruby with a TODO comment?

**Comment by flash-gordon** [comment]
Sure, I've made a branch for the issue https://github.com/rom-rb/rom-sql/commit/48d89fbb2f69c2b0ddb90e4b290b2c69979fd6a9
