### ISSUE TITLE
Relation's schema doesn't work with custom coercion rules

### ISSUE THREAD

**Issue by vbyno** [rom-rb/rom-sql#80]
I have a relation class:
```
class Relation < ROM::Relation[:sql]                                                       
  dataset :metrics
  register_as :metrics_relation
  
  schema do                                                        
    attribute :category, Types::String.default { 'default category' }
  end
end
```
When I try to insert new record into database I get an error:
```
=> metrics_relation.insert(params_hash.except(:category))
=> Sequel::DatabaseError: Mysql2::Error: Field 'category' doesn't have a default value
from .../gems/sequel-4.37.0/lib/sequel/adapters/mysql2.rb:137:in `query'
```
`infer: true` works as expected

I use `rom-sql 0.8.0`, `rom-repository 0.3.1`, `dry-types 0.8.1`

**Comment by solnic** [comment]
`Relation#insert` bypass schema types, please use a command instead, it'll work with types. I can understand that this may be surprising but we need a low-level API for inserting/updating/deleting data too, that doesn't use any external tools for value processing. That's why we have commands which provide lots of additional features.
